"""Pine Script converter — orchestrates parsing, codegen, and validation.

Pure code transpilation (NO LLM). Converts Pine Script v5 to Python Strategy
plugins with metadata extraction and validation.
"""

from __future__ import annotations

import ast
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Tuple

from .codegen import PineCodeGenerator
from .parser import PineScriptParser


class PineScriptConverter:
    """Convert Pine Script v5 to Platform Strategy.

    NO LLM. Pure code transpilation.
    """

    def __init__(
        self,
        parser: PineScriptParser | None = None,
        codegen: PineCodeGenerator | None = None,
    ):
        self.parser = parser or PineScriptParser()
        self.codegen = codegen or PineCodeGenerator()

    def convert(
        self,
        pine_code: str,
        strategy_name: str | None = None,
    ) -> Tuple[str, dict]:
        """Convert Pine Script to Python Strategy.

        Args:
            pine_code: Raw Pine Script v5 source code
            strategy_name: Optional override for the generated class name

        Returns:
            Tuple of (python_code, metadata)

        Raises:
            PineConversionError: If parsing or generation fails
        """
        # 1. Extract strategy name from Pine if not provided. User-provided
        # names are sanitized too — they become a Python class name, so
        # "Outside Bar Strategy" must become "OutsideBarStrategy".
        if not strategy_name:
            match = re.search(r'strategy\(["\']([^"\']+)', pine_code)
            strategy_name = match.group(1) if match else "ImportedStrategy"
        strategy_name = self._sanitize_class_name(strategy_name) or "ImportedStrategy"

        # 2. Parse Pine Script to AST
        try:
            pine_ast = self.parser.parse(pine_code)
        except Exception as e:
            raise PineConversionError(f"Failed to parse Pine Script: {e}") from e

        # 3. Generate Python code
        try:
            python_code = self.codegen.generate(pine_ast, strategy_name)
        except Exception as e:
            raise PineConversionError(f"Failed to generate Python code: {e}") from e

        # 4. Validate generated code
        is_valid, error = self._validate_code(python_code)
        if not is_valid:
            raise PineConversionError(f"Generated code validation failed: {error}")

        # 5. Extract metadata
        metadata = {
            "original_name": strategy_name,
            "indicators_used": self._extract_indicators_list(pine_ast),
            "has_long": self._has_long_trades(pine_ast),
            "has_short": self._has_short_trades(pine_ast),
            "complexity": self._estimate_complexity(pine_ast),
            "readable": self._extract_readable_summary(pine_ast, pine_code),
        }
        return python_code, metadata

    def save_as_plugin(
        self,
        python_code: str,
        strategy_name: str,
        metadata: dict,
        segment: str | None = None,
    ) -> Path:
        """Save generated strategy as plugin.

        Args:
            python_code: Generated Python strategy code
            strategy_name: Name for the strategy
            metadata: Conversion metadata dict
            segment: Optional capital-partition name (config/segments.yaml).
                issues.txt S2: every saved strategy is linked to a segment so
                backtest → paper → live all spawn into the same partition;
                the class-level ``default_segment`` is what the spawn form
                preselects.

        Returns:
            Path to the saved plugin file
        """
        plugin_dir = Path("plugins/strategies")
        plugin_dir.mkdir(parents=True, exist_ok=True)

        # The plugin loader derives a module name from the filename, so it
        # must be a valid Python identifier: no spaces or special characters.
        safe = re.sub(r"[^a-z0-9_]", "_", strategy_name.lower())
        safe = re.sub(r"_+", "_", safe).strip("_") or "imported_strategy"
        filename = f"{safe}_imported.py"
        filepath = plugin_dir / filename

        # Add header comment
        header = f'''"""
Auto-generated from Pine Script v5
Generated: {datetime.now().isoformat()}

Original Strategy: {metadata['original_name']}
Indicators: {', '.join(metadata['indicators_used'])}
Supports: {'Long' if metadata['has_long'] else ''} {'Short' if metadata['has_short'] else ''}

DO NOT EDIT THIS FILE DIRECTLY.
Re-convert from Pine Script if changes needed.
"""

from backtest.strategy.base import Strategy

import pandas as pd
import numpy as np

'''

        full_code = header + python_code

        if segment:
            full_code = self._inject_default_segment(full_code, segment)
            syntax_error = None
            try:
                ast.parse(full_code)
            except SyntaxError as exc:
                syntax_error = exc
            if syntax_error:
                raise PineConversionError(
                    f"Failed to link segment {segment!r} to the generated "
                    f"strategy: {syntax_error}"
                )

        filepath.write_text(full_code, encoding="utf-8")

        return filepath

    @staticmethod
    def _inject_default_segment(python_code: str, segment: str) -> str:
        """Add ``default_segment`` to the generated class body.

        Anchored on a class-body line the codegen always emits (version →
        author → name, first match wins). The segment name is sanitized to
        the identifier charset the spawn form produces, so a crafted string
        can never break out of the quoted literal.
        """
        seg = re.sub(r"[^a-z0-9_]", "", str(segment).strip().lower())
        if not seg:
            raise PineConversionError(f"invalid segment name: {segment!r}")
        for anchor in ('    version = "', '    author = "', '    name = "'):
            idx = python_code.find(anchor)
            if idx != -1:
                end = python_code.find("\n", idx)
                end = len(python_code) if end == -1 else end + 1
                insert = f"    default_segment = \"{seg}\"\n"
                return python_code[:end] + insert + python_code[end:]
        raise PineConversionError(
            "generated strategy is missing its metadata block — cannot link a segment"
        )

    def _validate_code(self, code: str) -> Tuple[bool, str]:
        """Validate generated Python code."""
        # 1. Syntax check
        try:
            ast.parse(code)
        except SyntaxError as e:
            return False, f"Syntax error: {e}"

        # 2. Required methods — the plugin contract is entries()/generate_signals()
        if "def entries" not in code and "def generate_signals" not in code:
            return False, "Missing entries()/generate_signals() method"

        # 3. Security check
        dangerous = [
            "open(",
            "urllib",
            "requests",
            "subprocess",
            "eval(",
            "exec(",
            "__import__",
            "os.system",
        ]
        for pattern in dangerous:
            if pattern in code:
                return False, f"Dangerous pattern detected: {pattern}"

        return True, ""

    def _sanitize_class_name(self, name: str) -> str:
        """Convert 'EMA Cross' → 'EmaCross' and keep 'MyCustomStrategy' as typed.

        ``word.capitalize()`` lower-cases everything after the first letter, so
        a PascalCase name from the Strategy Builder's custom-name field came out
        as "Mycustomstrategy". A word that is already mixed case is a legal
        identifier the user chose — leave it alone (apart from the first letter).
        """
        clean = re.sub(r"[^a-zA-Z0-9\s]", "", name)
        parts = []
        for word in clean.split():
            if word.isupper() or word.islower():
                parts.append(word.capitalize())
            else:
                parts.append(word[0].upper() + word[1:])
        return "".join(parts)

    def _extract_indicators_list(self, ast: Dict) -> list[str]:
        """Extract list of indicator names used."""
        indicators = []
        for statement in ast.get("statements", []):
            # Check both top-level indicator calls and those inside if statements
            if statement.get("type") == "indicator_call":
                namespace = statement.get("namespace", "ta")
                func = statement.get("function", "")
                indicators.append(f"{namespace}.{func}")
            elif statement.get("type") == "if_statement":
                # Check inside if/else bodies
                for body_list in [statement.get("body", []), statement.get("else_body", [])]:
                    for inner in body_list:
                        if inner.get("type") == "indicator_call":
                            namespace = inner.get("namespace", "ta")
                            func = inner.get("function", "")
                            indicators.append(f"{namespace}.{func}")
        return sorted(set(indicators))

    def _has_long_trades(self, ast: Dict) -> bool:
        """Check if strategy has long entry signals."""
        for statement in ast.get("statements", []):
            if statement.get("type") == "if_statement":
                for inner in statement.get("body", []):
                    if inner.get("type") == "strategy_call":
                        if (
                            inner["function"] == "strategy.entry"
                            and "long" in inner.get("direction", "")
                        ):
                            return True
        return False

    def _has_short_trades(self, ast: Dict) -> bool:
        """Check if strategy has short entry signals."""
        for statement in ast.get("statements", []):
            if statement.get("type") == "if_statement":
                for inner in statement.get("body", []):
                    if inner.get("type") == "strategy_call":
                        if (
                            inner["function"] == "strategy.entry"
                            and "short" in inner.get("direction", "")
                        ):
                            return True
        return False

    def _estimate_complexity(self, ast: Dict) -> str:
        """Estimate strategy complexity (simple/medium/complex)."""
        indicators = len(self._extract_indicators_list(ast))
        conditions = sum(
            1
            for s in ast.get("statements", [])
            if s.get("type") == "if_statement"
        )

        score = indicators * 2 + conditions
        if score < 5:
            return "simple"
        elif score < 15:
            return "medium"
        return "complex"

    def _condition_text(self, cond: Dict) -> str:
        """Render a parsed Pine condition as a short readable phrase."""
        if not isinstance(cond, dict):
            return str(cond) if cond else ""
        ctype = cond.get("type", "")
        if ctype == "function_call":
            args = ", ".join(str(a) for a in cond.get("args", []))
            return f"{cond.get('namespace', '')}.{cond.get('function', '')}({args})"
        if ctype == "change_flip":
            return (f"{cond.get('variable', '')} flips "
                    f"{cond.get('operator', '')} {cond.get('value', '')}")
        if ctype == "comparison":
            return (f"{cond.get('left', '')} {cond.get('operator', '')} "
                    f"{cond.get('right', '')}")
        if ctype == "identifier":
            return str(cond.get("name", ""))
        return str(ctype)

    def _extract_readable_summary(self, ast: Dict, pine_code: str) -> dict:
        """Extract a human-readable summary of a strategy from its Pine AST.

        Covers the issues.txt S1 requirements: entry criteria, entry strike
        (options), take profit and stop loss. Any field the user left out is
        flagged in ``missing`` (computed server-side) so the UI and the API
        agree on what is absent. Strike/expiry are only required when the
        script looks option-related — an equity strategy has no strike, and
        requiring one used to block every equity Save.
        """
        entry = exit_ = take_profit = stop_loss = entry_strike = expiry = None

        # Variable → expression text, so `stop=sl_price` can be shown as the
        # actual formula ("close * 0.98") instead of a bare variable name.
        var_text: Dict[str, str] = {}
        for stmt in ast.get("statements", []):
            stype = stmt.get("type")
            if stype == "assignment":
                var_text[stmt.get("name", "")] = str(stmt.get("value", ""))
            elif stype == "indicator_call":
                var_text[stmt.get("var_name", "")] = (
                    f"{stmt.get('namespace', 'ta')}.{stmt.get('function', '')}("
                    + ", ".join(str(a) for a in stmt.get("args", []))
                    + ")"
                )

        def resolve(token: str, depth: int = 0) -> str:
            tok = str(token).strip()
            if depth < 3 and tok in var_text:
                return resolve(var_text[tok], depth + 1)
            return tok

        def all_calls(kind: str):
            """Yield (enclosing if-condition text | None, call statement)."""
            for stmt in ast.get("statements", []):
                if stmt.get("type") == "strategy_call" and stmt.get("function") == kind:
                    yield None, stmt
                elif stmt.get("type") == "if_statement":
                    for inner in list(stmt.get("body", [])) + list(stmt.get("else_body", [])):
                        if inner.get("type") == "strategy_call" and inner.get("function") == kind:
                            yield self._condition_text(stmt.get("condition")), inner

        # 1. Entry criteria: the condition(s) feeding strategy.entry.
        for cond, call in all_calls("strategy.entry"):
            entry = entry or cond or call.get("direction", "")

        # 2. Exit: strategy.close triggers a reversal/exits.
        for cond, call in all_calls("strategy.close"):
            exit_ = exit_ or cond or call.get("name", "")

        # 3. Take profit / stop loss — prefer strategy.exit named args
        #    (limit/profit → TP, stop/loss → SL); fall back to the *_tp /
        #    *_sl variable-name convention for older scripts.
        for _cond, call in all_calls("strategy.exit"):
            params = call.get("exit_params", {}) or {}
            tp = params.get("limit") or params.get("profit")
            sl = params.get("stop") or params.get("loss")
            if tp and take_profit is None:
                take_profit = f"limit = {resolve(tp)}"
            if sl and stop_loss is None:
                stop_loss = f"stop = {resolve(sl)}"
        for stmt in ast.get("statements", []):
            if stmt.get("type") not in ("indicator_call", "assignment"):
                continue
            var = stmt.get("var_name") or stmt.get("name") or ""
            if take_profit is None and ("take_profit" in var or "takeprofit" in var
                                        or var.endswith("tp") or var.endswith("tp_price")):
                take_profit = f"{var} = {resolve(var)}"
            if stop_loss is None and ("stop_loss" in var or "stoploss" in var
                                      or var.endswith("sl") or var.endswith("sl_price")):
                stop_loss = f"{var} = {resolve(var)}"

        # 4. Option strike / expiry: look for integer literals near the words
        # strike/expiry in the source (Pine option strategies hardcode them).
        # Each match is filed under the keyword it actually carries — an
        # expiry literal is not a strike and vice versa.
        for pat in re.finditer(
            r"(?i)(\bstrike\b|expiry)[^;]{0,80}?(\d{1,3}(?:\.\d{1,2})?)", pine_code
        ):
            keyword = pat.group(1).lower()
            if entry_strike is None and "strike" in keyword:
                entry_strike = pat.group(2)
            if expiry is None and "expiry" in keyword:
                expiry = pat.group(2)

        # Heuristic option-ness: a script that talks about strikes/CE/PE/options
        # must state its strike/expiry; equity scripts are not blocked by
        # fields they do not have.
        is_options = bool(
            entry_strike is not None
            or re.search(r"(?i)\bstrike\b|\bCE\b|\bPE\b|\boptions?\b", pine_code)
        )

        missing: list[str] = []
        if not entry:
            missing.append("entry")
        if not take_profit:
            missing.append("take profit")
        if not stop_loss:
            missing.append("stop loss")
        if is_options:
            if not entry_strike:
                missing.append("entry strike")
            if not expiry:
                missing.append("expiry")

        return {
            "entry": entry,
            "exit": exit_,
            "take_profit": take_profit,
            "stop_loss": stop_loss,
            "entry_strike": entry_strike,
            "expiry": expiry,
            "is_options": is_options,
            "missing": missing,
        }


class PineConversionError(Exception):
    """Raised when Pine Script conversion fails."""

    pass
