"""Pine Script converter — orchestrates parsing, codegen, and validation.

Pure code transpilation (NO LLM). Converts Pine Script v5 to Python Strategy
plugins with metadata extraction and validation.
"""

from __future__ import annotations

import ast
import re
from datetime import datetime
from pathlib import Path
from typing import Dict, Tuple

from .codegen import PineCodeGenerator
from .parser import PineScriptParser


class PineScriptConverter:
    """Convert Pine Script v5 to Platform Strategy.

    NO LLM. Pure code transpilation.
    """

    def __init__(
        self,
        parser: PineScriptParser | None = None,
        codegen: PineCodeGenerator | None = None,
    ):
        self.parser = parser or PineScriptParser()
        self.codegen = codegen or PineCodeGenerator()

    def convert(
        self,
        pine_code: str,
        strategy_name: str | None = None,
    ) -> Tuple[str, dict]:
        """Convert Pine Script to Python Strategy.

        Args:
            pine_code: Raw Pine Script v5 source code
            strategy_name: Optional override for the generated class name

        Returns:
            Tuple of (python_code, metadata)

        Raises:
            PineConversionError: If parsing or generation fails
        """
        # 1. Extract strategy name from Pine if not provided. User-provided
        # names are sanitized too — they become a Python class name, so
        # "Outside Bar Strategy" must become "OutsideBarStrategy".
        if not strategy_name:
            match = re.search(r'strategy\(["\']([^"\']+)', pine_code)
            strategy_name = match.group(1) if match else "ImportedStrategy"
        strategy_name = self._sanitize_class_name(strategy_name) or "ImportedStrategy"

        # 2. Parse Pine Script to AST
        try:
            pine_ast = self.parser.parse(pine_code)
        except Exception as e:
            raise PineConversionError(f"Failed to parse Pine Script: {e}") from e

        # 3. Generate Python code
        try:
            python_code = self.codegen.generate(pine_ast, strategy_name)
        except Exception as e:
            raise PineConversionError(f"Failed to generate Python code: {e}") from e

        # 4. Validate generated code
        is_valid, error = self._validate_code(python_code)
        if not is_valid:
            raise PineConversionError(f"Generated code validation failed: {error}")

        # 5. Extract metadata
        metadata = {
            "original_name": strategy_name,
            "indicators_used": self._extract_indicators_list(pine_ast),
            "has_long": self._has_long_trades(pine_ast),
            "has_short": self._has_short_trades(pine_ast),
            "complexity": self._estimate_complexity(pine_ast),
        }

        return python_code, metadata

    def save_as_plugin(
        self,
        python_code: str,
        strategy_name: str,
        metadata: dict,
    ) -> Path:
        """Save generated strategy as plugin.

        Args:
            python_code: Generated Python strategy code
            strategy_name: Name for the strategy
            metadata: Conversion metadata dict

        Returns:
            Path to the saved plugin file
        """
        plugin_dir = Path("plugins/strategies")
        plugin_dir.mkdir(parents=True, exist_ok=True)

        # The plugin loader derives a module name from the filename, so it
        # must be a valid Python identifier: no spaces or special characters.
        safe = re.sub(r"[^a-z0-9_]", "_", strategy_name.lower())
        safe = re.sub(r"_+", "_", safe).strip("_") or "imported_strategy"
        filename = f"{safe}_imported.py"
        filepath = plugin_dir / filename

        # Add header comment
        header = f'''"""
Auto-generated from Pine Script v5
Generated: {datetime.now().isoformat()}

Original Strategy: {metadata['original_name']}
Indicators: {', '.join(metadata['indicators_used'])}
Supports: {'Long' if metadata['has_long'] else ''} {'Short' if metadata['has_short'] else ''}

DO NOT EDIT THIS FILE DIRECTLY.
Re-convert from Pine Script if changes needed.
"""

from backtest.strategy.base import Strategy

import pandas as pd
import numpy as np

'''

        full_code = header + python_code

        filepath.write_text(full_code, encoding="utf-8")

        return filepath

    def _validate_code(self, code: str) -> Tuple[bool, str]:
        """Validate generated Python code."""
        # 1. Syntax check
        try:
            ast.parse(code)
        except SyntaxError as e:
            return False, f"Syntax error: {e}"

        # 2. Required methods — the plugin contract is entries()/generate_signals()
        if "def entries" not in code and "def generate_signals" not in code:
            return False, "Missing entries()/generate_signals() method"

        # 3. Security check
        dangerous = [
            "open(",
            "urllib",
            "requests",
            "subprocess",
            "eval(",
            "exec(",
            "__import__",
            "os.system",
        ]
        for pattern in dangerous:
            if pattern in code:
                return False, f"Dangerous pattern detected: {pattern}"

        return True, ""

    def _sanitize_class_name(self, name: str) -> str:
        """Convert 'EMA Cross' → 'EmaCross'."""
        # Remove special chars, title case, remove spaces
        clean = re.sub(r"[^a-zA-Z0-9\s]", "", name)
        return "".join(word.capitalize() for word in clean.split())

    def _extract_indicators_list(self, ast: Dict) -> list[str]:
        """Extract list of indicator names used."""
        indicators = []
        for statement in ast.get("statements", []):
            # Check both top-level indicator calls and those inside if statements
            if statement.get("type") == "indicator_call":
                namespace = statement.get("namespace", "ta")
                func = statement.get("function", "")
                indicators.append(f"{namespace}.{func}")
            elif statement.get("type") == "if_statement":
                # Check inside if/else bodies
                for body_list in [statement.get("body", []), statement.get("else_body", [])]:
                    for inner in body_list:
                        if inner.get("type") == "indicator_call":
                            namespace = inner.get("namespace", "ta")
                            func = inner.get("function", "")
                            indicators.append(f"{namespace}.{func}")
        return sorted(set(indicators))

    def _has_long_trades(self, ast: Dict) -> bool:
        """Check if strategy has long entry signals."""
        for statement in ast.get("statements", []):
            if statement.get("type") == "if_statement":
                for inner in statement.get("body", []):
                    if inner.get("type") == "strategy_call":
                        if (
                            inner["function"] == "strategy.entry"
                            and "long" in inner.get("direction", "")
                        ):
                            return True
        return False

    def _has_short_trades(self, ast: Dict) -> bool:
        """Check if strategy has short entry signals."""
        for statement in ast.get("statements", []):
            if statement.get("type") == "if_statement":
                for inner in statement.get("body", []):
                    if inner.get("type") == "strategy_call":
                        if (
                            inner["function"] == "strategy.entry"
                            and "short" in inner.get("direction", "")
                        ):
                            return True
        return False

    def _estimate_complexity(self, ast: Dict) -> str:
        """Estimate strategy complexity (simple/medium/complex)."""
        indicators = len(self._extract_indicators_list(ast))
        conditions = sum(
            1
            for s in ast.get("statements", [])
            if s.get("type") == "if_statement"
        )

        score = indicators * 2 + conditions
        if score < 5:
            return "simple"
        elif score < 15:
            return "medium"
        return "complex"


class PineConversionError(Exception):
    """Raised when Pine Script conversion fails."""

    pass
