"""
Auto-generated from Pine Script v5
Generated: 2026-09-29T14:50:41.513272

Original Strategy: OutsideBarStrategy
Indicators: 
Supports: Long Short

DO NOT EDIT THIS FILE DIRECTLY.
Re-convert from Pine Script if changes needed.
"""

from backtest.strategy.base import Strategy

import pandas as pd
import numpy as np

"""
Auto-generated from Pine Script v5 by the Strategy Builder.

Long-only platform: Pine short entries are OR-ed into entries.
Plot/draw statements ignored (no visualization).
"""

from backtest.strategy.base import Strategy

import numpy as np
import pandas as pd




class OutsideBarStrategy(Strategy):
    """
    Auto-generated from Pine Script v5 by the Strategy Builder.

    Entries are OR-ed across all Pine entry conditions; the platform
    equity model is long-only, so short entries are folded into the
    same entries series (flagged below).
    """

    name = "outsidebarstrategy"
    description = "Imported from Pine Script v5 via Strategy Builder"
    version = "1.0"
    author = "Pine Converter"

    params: dict = {}  # Pine script declared no input() parameters

    def entries(self, df: pd.DataFrame) -> pd.Series:
        high = df["high"].values
        low = df["low"].values
        close = df["close"].values
        n = len(close)

        # Pine inputs → instance params (bound by Strategy.__init__)

        # Indicator calculations
        # No indicators to precompute
        # Entry conditions (long-only platform: shorts folded in)
        long_entries = np.zeros(n, dtype=bool)
        short_entries = np.zeros(n, dtype=bool)
        long_entries |= (high > high[1] and low < low[1])
        short_entries |= (high > high[1] and low < low[1])  # short folded in (long-only platform)
        # The base class turns entries/exits into generate_signals().
        return pd.Series(long_entries | short_entries, index=df.index)
