"""
Auto-generated from Pine Script v5
Generated: 2026-09-29T14:26:57.464865

Original Strategy: SupertrendStrategy
Indicators: ta.supertrend
Supports: Long Short

DO NOT EDIT THIS FILE DIRECTLY.
Re-convert from Pine Script if changes needed.
"""

from backtest.strategy.base import Strategy

import pandas as pd
import numpy as np

"""
Auto-generated from Pine Script v5 by the Strategy Builder.

Long-only platform: Pine short entries are OR-ed into entries.
Plot/draw statements ignored (no visualization).
"""

from backtest.strategy.base import Strategy

import numpy as np
import pandas as pd


def _tr_atr(high, low, close, period):
    n = len(close)
    tr = np.empty(n)
    tr[0] = high[0] - low[0]
    for i in range(1, n):
        tr[i] = max(high[i] - low[i], abs(high[i] - close[i - 1]),
                 abs(low[i] - close[i - 1]))
    atr = np.empty(n)
    atr[0] = tr[0]
    for i in range(1, n):
        atr[i] = (atr[i - 1] * (period - 1) + tr[i]) / period
    return atr


def _supertrend(high, low, close, period, factor):
    """Pine ta.supertrend: +1 bull, -1 bear."""
    n = len(close)
    atr = _tr_atr(high, low, close, period)
    hl2 = (high + low) / 2.0
    upper = hl2 + factor * atr
    lower = hl2 - factor * atr
    direction = np.ones(n, dtype=int)
    for i in range(1, n):
        if not (upper[i] < upper[i - 1] or close[i - 1] > upper[i - 1]):
            upper[i] = upper[i - 1]
        if not (lower[i] > lower[i - 1] or close[i - 1] < lower[i - 1]):
            lower[i] = lower[i - 1]
        if direction[i - 1] == 1:
            direction[i] = -1 if close[i] < lower[i] else 1
        else:
            direction[i] = 1 if close[i] > upper[i] else -1
    return direction


def _supertrend_line(high, low, close, period, factor, direction):
    """The supertrend price line, given a direction array."""
    atr = _tr_atr(high, low, close, period)
    hl2 = (high + low) / 2.0
    return np.where(direction == 1, hl2 - factor * atr, hl2 + factor * atr)


def _changed(arr):
    arr = np.asarray(arr)
    out = np.zeros(len(arr), dtype=arr.dtype)
    out[1:] = arr[1:] - arr[:-1]
    return out

class SupertrendStrategy(Strategy):
    """
    Auto-generated from Pine Script v5 by the Strategy Builder.

    Entries are OR-ed across all Pine entry conditions; the platform
    equity model is long-only, so short entries are folded into the
    same entries series (flagged below).
    """

    name = "supertrendstrategy"
    description = "Imported from Pine Script v5 via Strategy Builder"
    version = "1.0"
    author = "Pine Converter"

    params = {
        "atrPeriod": {
            "default": 10,
            "type": "int",
            "label": "Atr Length",
            "tooltip": "Pine Script input()",
        },
        "factor": {
            "default": 3.0,
            "type": "float",
            "label": "Factor",
            "tooltip": "Pine Script input()",
        },
    }

    def entries(self, df: pd.DataFrame) -> pd.Series:
        high = df["high"].values
        low = df["low"].values
        close = df["close"].values
        n = len(close)

        # Pine inputs → instance params (bound by Strategy.__init__)
        atrPeriod = self.atrPeriod
        factor = self.factor

        # Indicator calculations
        direction = _supertrend(high, low, close, int(atrPeriod), float(factor))
        _ = _supertrend_line(high, low, close, int(atrPeriod), float(factor), direction)
        # Entry conditions (long-only platform: shorts folded in)
        long_entries = np.zeros(n, dtype=bool)
        short_entries = np.zeros(n, dtype=bool)
        long_entries |= _changed(_supertrend(high, low, close, int(atrPeriod), float(factor))) < 0
        short_entries |= _changed(_supertrend(high, low, close, int(atrPeriod), float(factor))) > 0  # short folded in (long-only platform)
        # The base class turns entries/exits into generate_signals().
        return pd.Series(long_entries | short_entries, index=df.index)
